### ISSUE TITLE
add `py.typed` to root of package

### ISSUE THREAD

**Issue by pappasam** [krassowski/docstring-to-markdown#4]
I'm planning to incorporate this into `jedi-language-server`; it'd be great if you added a `py.typed` to the root of the project (once you've verified that your types pass mypy) so I don't need to ignore this package with `mypy.ini`!

**Comment by krassowski** [comment]
Done in v0.4. Also a little gif to show off where this is currently at:

![demo](https://user-images.githubusercontent.com/5832902/107853917-6f411380-6e10-11eb-9af3-91c775db42d8.gif)
